name: cellpose
dependencies:
  - python>3.4,<3.8
  - pip
  - pip:
    - PyQt5
    - PyQt5.sip
    - numpy==1.20
    - numba>=0.43.1
    - scipy
    - torch>=1.6
    - opencv-python-headless
    - pyqtgraph>=0.11.0rc0
    - natsort
    - google-cloud-storage
    - tqdm
    - tifffile
    - cellpose
    - scikit-image
    - pandas 
    
  